version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/server
    binary: bin/server
    ldflags:
      - -s -w
      - -X {{.ModulePath}}/internal/version.Version={{.Version}}
      - -X {{.ModulePath}}/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64

archives:
  - format: tar.gz
    name_template: >-
      {{.ProjectName}}_
      {{.Os}}_
      {{.Arch}}

dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - '{{.ProjectName}}:latest'
      - '{{.ProjectName}}:{{.Version}}'
    build_flag_templates:
      - "--build-arg=CREATED={{.Date}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=TAG={{.Tag}}"
      - "--build-arg=REVISION={{.ShortCommit}}"
    skip_push: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
